DROP DATABASE IF EXISTS nose;
DROP USER IF EXISTS student;
CREATE USER student WHITH PASSWORD 'himitu';
CREATE DATABASE nose OWNER student ENCODING 'UTF8';

DROP TABLE IF EXISTS star;
CREATE TABLE star (
  code INTEGER PRIMARY KEY,
  star TEXT
);
